### ISSUE TITLE
Ошибка при загрузке главной страницы

### ISSUE THREAD

**Issue by deviatovae** [ViktoriyaKo/spotify-clone#29]
Шаги:
1. Зайти на деплой
1. Зарегистрироваться
1. Войти

Текущий результат:
- На странице `/home` отображается ошибка
```
TypeError: Cannot read properties of undefined (reading 'items')
    at Object.getNewReleases (/app/dist/spoApi/getCollections.js:111:24)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /app/dist/controllers/viewController.js:18:25
```

Ожидаемый результат:
- Страница `/home` открывается без ошибок

**Comment by ViktoriyaKo** [comment]
Добрый день!

Данная ошибка возникает в деплое из-за CORS Spotify. В PR https://github.com/ViktoriyaKo/spotify-clone/pull/27 сделали инструкцию:
https://github.com/ViktoriyaKo/spotify-clone/blob/main/README.md

На данном этапе нужно изменить в адресной строке home на login следующим образом:
https://web-production-d943.up.railway.app/login
